import '@radix-ui/themes/styles.css'
import { Theme } from '@radix-ui/themes'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='zh-CN'>
      <body>
        <Theme
          appearance='light'
          accentColor='blue'
          grayColor='slate'
          scaling='100%'
          radius='medium'
        >
          {children}
        </Theme>
      </body>
    </html>
  )
}
