import '@radix-ui/themes/styles.css'
import { Theme, Flex } from '@radix-ui/themes'
import type { Metadata } from 'next'
import './globals.css'
import { Sidebar } from '@/components/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='zh-CN'>
      <body>
        <Theme
          appearance='light'
          accentColor='iris'
          grayColor='slate'
          scaling='100%'
          radius='medium'
        >
          <Flex>
            <Sidebar />
            <main style={{ width: '100%' }}>{children}</main>
          </Flex>
        </Theme>
      </body>
    </html>
  )
}
